tab_spaces = 2
max_width = 120
indent_style = "Block"
imports_indent = "Block"
group_imports = "StdExternalCrate"
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 20
trailing_comma = "Never"
control_brace_style = "AlwaysSameLine"
fn_args_layout = "Tall"
